#!/bin/bash

function start(){
	redis=$1;
	web=$2;
	if [[ "${redis}x" == "x" ]];then
		echo "pass ......"
		#redis-server ./redis-6379/redis.conf
	fi
	if [[ "${web}x" == "x" ]];then
		./webroot/web.py &
		ps > .pidfile && echo "server start ......"
		echo "start server,listening port 8082"
	else
		echo "the web is already runing"
		echo "start server,listening port 8082"
	fi
}
function stop(){
	redis=$1;
	web=$2;
	if [[ "${redis}x" != "x" ]];then
		echo "pass ......"
		#redis-cli shutdown
	fi
	if [[ "${web}x" != "x" ]];then
		pid=`cat .pidfile | grep "web.py" | awk '{print $1}'`
		kill -9 $pid && echo "server stop ......"
	fi
	echo "server has bean stop......"
}
if [[ $# != 1 ]];then
	echo "Usage: $0 [start|stop|restart]"
	exit -1
fi
redis=`netstat -lntp | grep "6379"`
web=`netstat -lntp | grep "8082"`
ttarg=$1;
if [[ "${ttarg}x" == "startx" ]];then
	start $redis $web
elif [[ "${ttarg}x" == "stopx" ]];then
	stop $redis $web
elif [[ "${ttarg}x" == "restartx" ]];then
	stop $redis $web
	start $redis $web
fi
