#!/bin/bash

function start(){
	web=$1;
	if [[ "${web}x" == "x" ]];then
		./fwebstr/web.py &
		ps > .pidfile && echo "server start ......"
		echo "start server,listening port 8082"
	else
		echo "the web is already runing"
		echo "start server,listening port 8082"
	fi
}
function stop(){
	web=$1;
	if [[ "${web}x" != "x" ]];then
		pid=`cat .pidfile | grep "web.py" | awk '{print $1}'`
		if [[ "${pid}x" != "x" ]];then
			kill -9 $pid && echo "server stop ......"
		fi
	fi
	echo "server has bean stop......"
}
if [[ $# != 1 ]];then
	echo "Usage: $0 [start|stop|restart]"
	exit -1
fi
web=`netstat -lntp | grep "8082"`
ttarg=$1;
if [[ "${ttarg}x" == "startx" ]];then
	start $web
elif [[ "${ttarg}x" == "stopx" ]];then
	stop $web
elif [[ "${ttarg}x" == "restartx" ]];then
	stop $web
	start $web
fi
